### ISSUE TITLE
Giao diện đồ họa hiển thị không đúng nếu scale màn hình lên 125%

### ISSUE THREAD

**Issue by nonqxt86** [vinadevs/VinaText#12]
Bác thử scale màn hình lên 125% và mở Preference -> General Settings rồi kéo xuống sẽ thấy nó như thế này ạ:

![Capture](https://user-images.githubusercontent.com/129592704/235249840-c77aa880-bb14-48e1-a047-6722f32250e7.PNG)

Em vẫn đang dùng Windows 8.1 trên con laptop cùi, màn hình nó lởm quá, nếu không scale lên sẽ rất khó đọc chữ ạ.

**Comment by vinadevs** [comment]
Cảm ơn bác, để em check lỗi này. :D

**Comment by nonqxt86** [comment]
> Cảm ơn bác, để em check lỗi này. :D

Em vừa mới lên bản 1.7 nhưng vẫn thế bác ạ.

**Comment by vinadevs** [comment]
Bác thử tải bản mới nhất nha, em fix rồi ạ.

**Comment by vinadevs** [comment]
Vâng, thanks bác.

**Comment by vinadevs** [comment]
> > Bác thử tải bản mới nhất nha, em fix rồi ạ.
> 
> Đã xem được đầy đủ rồi bác ạ, mặc dù kéo xuống nữa thì thấy toàn khoảng trống nhưng chắc phải vậy mới luôn luôn thấy đầy đủ được 😅
> 
> ![Capture1](https://user-images.githubusercontent.com/129592704/238650753-26607f39-c6b1-47f8-8410-eff653fddbf9.PNG) ![Capture2](https://user-images.githubusercontent.com/129592704/238650754-50f09520-64c9-4379-b7a1-65b70bddc371.PNG)

Ở bản 1.9 mới em đã fix hết các bug về scale 125% rồi nên giờ ổn rồi nha bác.
