### ISSUE TITLE
Windows Shell Extension support

### ISSUE THREAD

**Issue by 97tn** [vinadevs/VinaText#17]
Integrate to Windows Explorer's right click context menu's Open With. The application remains to be portable. You only have to distribute batch scripts to allow the users to manually install or uninstall the Shell Extensions. There are two ways to implement this. Either via Windows Registry (install and uninstall via .reg file) or via Shell Extensions DLL (install and uninstall via `regsvr32.exe`).

**Comment by vinadevs** [comment]
Yeah i have a roadmap for this feature also. I will be available soon.

**Comment by vinadevs** [comment]
This feature has added on v1.9
