### ISSUE TITLE
Opening multiple files from Windows Explorer using only one instance of the application

### ISSUE THREAD

**Issue by 97tn** [vinadevs/VinaText#18]
After this is added: https://github.com/vinadevs/VinaText/issues/17

Launching a new instance of the application for each files will be a nightmare. It will be unmanageable and could crash Windows.

**Comment by vinadevs** [comment]
Yes, the app only uses single instance at all now. Unless you move a tab to new instance by your purpose (right click on active tab).

**Comment by vinadevs** [comment]
This feature was already supported.
