### ISSUE TITLE
Editor Settings

### ISSUE THREAD

**Issue by 97tn** [vinadevs/VinaText#31]
`Editor Text Font Name` also allowed to select font size but that font size is not used, it has no effect since the font size is set by `Editor Text Font` (the name is confusing, why don't you make it `Editor Text Font Size`?). I also found that `Editor Text Font Name` dialog doesn't store previous setting (the application does remember the font setting, though), each time you open it the selections are reset.

**Comment by vinadevs** [comment]
Thanks for report, I will fix it for next release.

**Comment by vinadevs** [comment]
This bug was fixed in v1.9
