### ISSUE TITLE
Lỗi phím delete

### ISSUE THREAD

**Issue by nonqxt86** [vinadevs/VinaText#35]
Nhấn phím delete ở bất kì vị trí con trỏ nào dù là đầu dòng, cuối dòng hay giữa dòng thì nó cũng sẽ xóa cả dòng. Lỗi này bất tiện quá bác ạ.

**Comment by vinadevs** [comment]
Khá kỳ lạ là máy em không bị bác ạ @@. Để em check thử máy khác xem sao.

**Comment by yyokyfo** [comment]
I can confirm that this bug exists.

**Comment by vinadevs** [comment]
Hi, this bug was fixed in the latest release. Thank you.
