### ISSUE TITLE
`Text -> Remove -> Remove Selection` is redundancy

### ISSUE THREAD

**Issue by ghost** [vinadevs/VinaText#40]
Why did you add such a feature in the first place? You select a block of text then either Backspace or Delete will do the job. Why did you think we need a dedicated menu entry for it? Is it a sign of over-engineering?

Another problem with it is you are assigning the shortcut key for this feature is the Delete key. Shortcut keys always have two or more keys. Assigning a single key for shortcut key (except the Fn keys), is always inviting for problems. Not to mention that Delete is an essential key with a very well defined functionality.

**Comment by vinadevs** [comment]
Hi, this feature was removed in the latest release. Thank you.
