### ISSUE TITLE
How to completely clear the settings?

### ISSUE THREAD

**Issue by ghost** [vinadevs/VinaText#43]
I deleted the `VinaText-Portable-1.14` directory. I also deleted `%appdata%\VinaText`. I unpacked `VinaText-Portable-1.14.zip` to get a fresh version. Surprising enough for me, old settings are still there! I want to completely clear the settings. In case of I messed up everything, how could I factory reset it?

**Comment by vinadevs** [comment]
Hi, the reset all settings and window placements feature was supported in the latest release. Thank you.
