### ISSUE TITLE
Make it really portable!

### ISSUE THREAD

**Issue by ghost** [vinadevs/VinaText#44]
Finally, I found where VinaText is saving its settings. It's saving them in the Registry. Do you think it's something a portable software should do?

**Comment by ags1234** [comment]
Using version trVinaText-Portable-1.15.zip.
It is a misleading that this program is portable, it is simply not true. If one can run it without install does not mean it is portable. It is portable when it saves all the files it needs in the current directory, 
The settings are here: c:\Users\(user name)\AppData\Roaming\VinaText\
Making it really portable would be useful.

**Comment by vinadevs** [comment]
Hi All,

Thank you very much for your suggestions. 
Yes, I noted this issue and it will be improved in next versions. 
Have a nice weekend.

**Comment by ags1234** [comment]
@vinadevs Thank you for considering our observations.

**Comment by vinadevs** [comment]
Hi, this feature was supported in the latest release. Thank you.
