### ISSUE TITLE
Tool -> String Generator -> Generate Url Escape String

### ISSUE THREAD

**Issue by ghost** [vinadevs/VinaText#49]
What does this feature do? I don't understand! For example, I selected this Url:

https://creativecommons.org/publicdomain/zero/1.0/

It generated in Message Window two Chinese characters that Google Translate detected as Simplified Chinese characters but can't translate them. Not to mention that with the very same Url, each time I used the feature I got different results. It's always generated two random Chinese characters.

**Comment by vinadevs** [comment]
Hi, this function  is not useful so I removed it in the latest release. Thank you.
