### ISSUE TITLE
Hỗ trợ Pascal

### ISSUE THREAD

**Issue by nonqxt86** [vinadevs/VinaText#9]
Các em học sinh sẽ khỏi phải dán mắt vào cái giao diện xanh lè của Turbo Pascal nữa.

**Comment by vinadevs** [comment]
Chào bác,
Dạ hiện tại có hỗ trợ pascal rồi ấy bác, trong menu Code > Programing Language > Pascal.

**Comment by vinadevs** [comment]
Hi bác,
Version 1.3 đã support FreePascal, có thể dùng thay TurboPascal rồi.
![pascal](https://user-images.githubusercontent.com/75571755/233834055-9484dfa8-7a95-42ec-a775-1a1bc401b745.png)

**Comment by nonqxt86** [comment]
Cảm ơn bác nhé.
